"use client";
import { useState } from "react";
import { Archive, Pencil, Plus } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { useBusinessAccess } from "@/features/business/business-access-context";
import { MembersPageFrame } from "@/features/business/members-page-frame";
import { Pagination } from "@/features/business/pagination";
import { useArchiveCustomRole,useBusinessRoles } from "./hooks";
import { Badge,ErrorState,LoadingState,PermissionList } from "./shared";
import { RoleDialog } from "./role-dialog";
import type { BusinessRole } from "@/lib/access-api";

export function BusinessRolesPage({businessId}:{businessId:string}) { const {effectivePermissions}=useBusinessAccess(); const [page,setPage]=useState(1),limit=20; const [editing,setEditing]=useState<BusinessRole|null|undefined>(undefined);const [archive,setArchive]=useState<BusinessRole|null>(null);const canView=effectivePermissions.has("roles:view");const query=useBusinessRoles(businessId,page,limit,canView);const archiveMutation=useArchiveCustomRole(businessId,archive?.id??"");const available=Array.from(effectivePermissions);
 if(!canView)return <MembersPageFrame><ErrorState error={new Error("You do not have permission to view roles.")}/></MembersPageFrame>;
 return <MembersPageFrame><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-muted-foreground">Access control</p><h1 className="mt-1 text-3xl font-bold">Roles</h1><p className="mt-2 text-sm text-muted-foreground">Manage permission grants and explicit denials.</p></div>{effectivePermissions.has("roles:create")?<Button onClick={()=>setEditing(null)}><Plus/>Create role</Button>:null}</div><div className="mt-7">{query.isLoading?<LoadingState/>:query.error?<ErrorState error={query.error} onRetry={()=>query.refetch()}/>:query.data?.items.length?<div className="grid gap-4 lg:grid-cols-2">{query.data.items.map(role=><article key={role.id} className="rounded-xl border border-border bg-card p-5"><div className="flex justify-between gap-3"><div><div className="flex gap-2"><h2 className="font-semibold">{role.name}</h2><Badge>{role.type}</Badge>{role.status==="archived"?<Badge tone="bad">archived</Badge>:null}</div><p className="mt-1 text-xs text-muted-foreground">{role.key}</p></div>{role.type==="custom"&&role.status==="active"?<div className="flex gap-1">{effectivePermissions.has("roles:update")?<Button size="icon" variant="ghost" aria-label={`Edit ${role.name}`} onClick={()=>setEditing(role)}><Pencil/></Button>:null}{effectivePermissions.has("roles:delete")?<Button size="icon" variant="ghost" aria-label={`Archive ${role.name}`} onClick={()=>setArchive(role)}><Archive/></Button>:null}</div>:null}</div><div className="mt-4"><PermissionList permissions={role.permissions} denied={role.deniedPermissions}/></div></article>)}</div>:<p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No roles found.</p>}{query.data?<Pagination page={page} totalPages={query.data.pagination.totalPages} total={query.data.pagination.total} limit={limit} fetching={query.isFetching} onPage={setPage} onLimit={()=>{}}/>:null}</div><RoleDialog businessId={businessId} open={editing!==undefined} onOpenChange={v=>{if(!v)setEditing(undefined)}} role={editing} available={available}/><Dialog open={Boolean(archive)} onOpenChange={v=>{if(!v)setArchive(null)}}><DialogContent><DialogHeader><DialogTitle>Archive {archive?.name}?</DialogTitle><DialogDescription>This removes the custom role from future assignment. It does not permanently delete its history.</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setArchive(null)}>Cancel</Button><Button variant="destructive" disabled={archiveMutation.isPending} onClick={()=>archiveMutation.mutate(undefined,{onSuccess:()=>{toast.success("Role archived.");setArchive(null)},onError:e=>toast.error(e.message)})}>Archive role</Button></DialogFooter></DialogContent></Dialog></MembersPageFrame> }
