"use client";
import { useState } from "react";
import { Plus } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { useBusinessAccess } from "@/features/business/business-access-context";
import { MembersPageFrame } from "@/features/business/members-page-frame";
import { Pagination } from "@/features/business/pagination";
import { useApproveBusinessInvite,usePendingInviteApprovals,useRejectInviteApproval,useSentBusinessInvites } from "./hooks";
import { Badge,ErrorState,formatDateTime,LoadingState,PermissionList } from "./shared";
import { InviteDialog } from "./invite-dialog";
import type { BusinessInvite,InviteStatus } from "@/lib/access-api";

function tone(v:string){return v==="approved"||v==="accepted"||v==="sent"?"good":v==="failed"||v==="rejected"||v==="expired"||v==="revoked"?"bad":v==="pending"||v==="retrying"?"warn":"neutral" as const}
export function BusinessInvitesPage({businessId}:{businessId:string}) {const {effectivePermissions}=useBusinessAccess();const [page,setPage]=useState(1),[status,setStatus]=useState<InviteStatus|undefined>("pending"),[inviteOpen,setInviteOpen]=useState(false),[decision,setDecision]=useState<{invite:BusinessInvite;action:"approve"|"reject"}|null>(null);const canInvite=effectivePermissions.has("members:invite"),canApprove=effectivePermissions.has("roles:assign");const sent=useSentBusinessInvites(businessId,page,20,status,canInvite);const pending=usePendingInviteApprovals(businessId,1,20,canApprove);const approve=useApproveBusinessInvite(businessId),reject=useRejectInviteApproval(businessId);const mutation=decision?.action==="approve"?approve:reject;
 if(!canInvite)return <MembersPageFrame><ErrorState error={new Error("You do not have permission to manage invitations.")}/></MembersPageFrame>;
 const cards=(items:BusinessInvite[],approval=false)=>items.map(i=><article key={i.id} className="rounded-xl border border-border bg-card p-5"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{i.email}</h3><p className="mt-1 text-sm text-muted-foreground">{i.roleId.name} · invited by {i.invitedByUserId.name}</p></div><div className="flex gap-2"><Badge tone={tone(i.status)}>{i.status}</Badge><Badge tone={tone(i.approvalStatus)}>{i.approvalStatus.replaceAll("_"," ")}</Badge>{!approval?<Badge tone={tone(i.emailDeliveryStatus)}>{i.emailDeliveryStatus==="retrying"?"delivery pending":i.emailDeliveryStatus}</Badge>:null}</div></div>{approval?<div className="mt-4"><PermissionList permissions={i.roleId.permissions} denied={i.roleId.deniedPermissions}/><p className="mt-3 text-sm text-muted-foreground">Accepted {formatDateTime(i.acceptedAt)}. Approval is required because the requested role exceeds automatic assignment authority.</p><div className="mt-4 flex gap-2"><Button onClick={()=>setDecision({invite:i,action:"approve"})}>Approve access</Button><Button variant="outline" onClick={()=>setDecision({invite:i,action:"reject"})}>Reject</Button></div></div>:<><dl className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">Created</dt><dd>{formatDateTime(i.createdAt)}</dd></div><div><dt className="text-muted-foreground">Expires</dt><dd>{formatDateTime(i.expiresAt)}</dd></div></dl>{i.emailDeliveryStatus==="failed"&&i.emailFailureReason?<p className="mt-3 text-sm text-destructive">Delivery failed: {i.emailFailureReason}</p>:null}</>}</article>);
 return <MembersPageFrame><div className="flex justify-between gap-4"><div><p className="text-sm text-muted-foreground">Team access</p><h1 className="mt-1 text-3xl font-bold">Invitations</h1><p className="mt-2 text-sm text-muted-foreground">Track recipients, approval, and delivery status.</p></div><Button onClick={()=>setInviteOpen(true)}><Plus/>Invite member</Button></div>{canApprove?<section className="mt-8"><h2 className="text-xl font-bold">Pending membership approvals</h2><p className="mt-1 text-sm text-muted-foreground">Accepted invitations that require explicit role approval.</p><div className="mt-4 grid gap-3">{pending.isLoading?<LoadingState/>:pending.error?<ErrorState error={pending.error}/>:pending.data?.items.length?cards(pending.data.items,true):<p className="rounded-lg border border-dashed p-6 text-sm text-muted-foreground">No approvals are waiting.</p>}</div></section>:null}<section className="mt-8"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Sent invitations</h2><select aria-label="Invitation status" className="h-9 rounded-lg border border-input bg-background px-3 text-sm" value={status??""} onChange={e=>{setStatus((e.target.value||undefined) as InviteStatus|undefined);setPage(1)}}><option value="">All statuses</option>{["pending","accepted","rejected","expired","revoked"].map(s=><option key={s}>{s}</option>)}</select></div><div className="mt-4 grid gap-3">{sent.isLoading?<LoadingState/>:sent.error?<ErrorState error={sent.error} onRetry={()=>sent.refetch()}/>:sent.data?.items.length?cards(sent.data.items):<p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">No invitations found.</p>}</div>{sent.data?<Pagination page={page} totalPages={sent.data.pagination.totalPages} total={sent.data.pagination.total} limit={20} fetching={sent.isFetching} onPage={setPage} onLimit={()=>{}}/>:null}</section><InviteDialog businessId={businessId} open={inviteOpen} onOpenChange={setInviteOpen}/><Dialog open={Boolean(decision)} onOpenChange={v=>{if(!v)setDecision(null)}}><DialogContent><DialogHeader><DialogTitle>{decision?.action==="approve"?"Approve business access?":"Reject role approval?"}</DialogTitle><DialogDescription>{decision?.action==="approve"?`${decision.invite.email} will receive business access with the ${decision.invite.roleId.name} role.`:`${decision?.invite.email} will not receive business access from this invitation.`}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setDecision(null)}>Cancel</Button><Button variant={decision?.action==="approve"?"default":"destructive"} disabled={mutation.isPending} onClick={()=>decision&&mutation.mutate(decision.invite.id,{onSuccess:()=>{toast.success(decision.action==="approve"?"Access approved.":"Approval rejected.");setDecision(null)},onError:e=>toast.error(e.message)})}>Confirm</Button></DialogFooter></DialogContent></Dialog></MembersPageFrame>}
