"use client";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { useBusinessAccess } from "@/features/business/business-access-context";
import { useAssignableRoles,useCreateBusinessInvite } from "./hooks";
import { ErrorState,LoadingState,PermissionList } from "./shared";
import { RoleDialog } from "./role-dialog";

export function InviteDialog({businessId,open,onOpenChange}:{businessId:string;open:boolean;onOpenChange:(v:boolean)=>void}) { const {effectivePermissions}=useBusinessAccess();const roles=useAssignableRoles(businessId,1,100,open);const create=useCreateBusinessInvite(businessId);const [email,setEmail]=useState("");const [roleId,setRoleId]=useState("");const [roleOpen,setRoleOpen]=useState(false);const selected=roles.data?.items.find(r=>r.id===roleId);
 const close=()=>{setEmail("");setRoleId("");onOpenChange(false)};const submit=()=>{if(!/^\S+@\S+\.\S+$/.test(email))return toast.error("Enter a valid email address.");if(!roleId)return toast.error("Select a role.");create.mutate({email:email.trim(),roleId},{onSuccess:()=>{toast.success("Invitation sent. Email delivery is pending.");close()},onError:e=>toast.error(e.message)})};
 return <><Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Invite a team member</DialogTitle><DialogDescription>Choose an assignable role and review its access before sending.</DialogDescription></DialogHeader><label className="space-y-1 text-sm font-medium">Email address<Input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="person@example.com"/></label>{roles.isLoading?<LoadingState/>:roles.error?<ErrorState error={roles.error} onRetry={()=>roles.refetch()}/>:<label className="space-y-1 text-sm font-medium">Role<select className="h-9 w-full rounded-lg border border-input bg-background px-3" value={roleId} onChange={e=>setRoleId(e.target.value)}><option value="">Select a role</option>{roles.data?.items.filter(r=>r.key!=="owner").map(r=><option key={r.id} value={r.id}>{r.name} · {r.type}</option>)}</select></label>}{selected?<div className="rounded-lg border border-border bg-muted/40 p-4"><PermissionList permissions={selected.permissions} denied={selected.deniedPermissions}/>{selected.requiresApproval?<p className="mt-3 rounded-md bg-amber-500/10 p-3 text-sm text-amber-800 dark:text-amber-200">This role requires approval. The recipient may accept, but membership remains pending until an authorized role approver approves it.</p>:null}</div>:null}{effectivePermissions.has("roles:create")?<Button variant="link" className="justify-start px-0" onClick={()=>setRoleOpen(true)}>Create a custom role</Button>:null}<DialogFooter><Button variant="outline" onClick={close}>Cancel</Button><Button disabled={create.isPending||!selected} onClick={submit}>{create.isPending?"Sending…":"Send invitation"}</Button></DialogFooter></DialogContent></Dialog><RoleDialog businessId={businessId} open={roleOpen} onOpenChange={setRoleOpen} available={Array.from(effectivePermissions)} onCreated={r=>setRoleId(r.id)}/></> }
