"use client";
import { useState } from "react";
import Link from "next/link";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Pagination } from "@/features/business/pagination";
import { useAcceptBusinessInvite,useReceivedBusinessInvites,useRejectBusinessInvite } from "./hooks";
import { Badge,ErrorState,formatDateTime,LoadingState,PermissionList } from "./shared";
import type { InviteStatus } from "@/lib/access-api";

export function ReceivedInvitesPage(){const [page,setPage]=useState(1),[status,setStatus]=useState<InviteStatus|undefined>("pending");const query=useReceivedBusinessInvites(page,20,status);const accept=useAcceptBusinessInvite(),reject=useRejectBusinessInvite();const pendingId=accept.variables??reject.variables;
 const act=(id:string,kind:"accept"|"reject")=>{const mutation=kind==="accept"?accept:reject;mutation.mutate(id,{onSuccess:(result)=>{if(kind==="accept"&&"meta" in result)toast.success(result.meta.membershipCreated?"Invitation accepted. Business access is ready.":"Invitation accepted. Access is awaiting role approval.");else toast.success("Invitation rejected.")},onError:e=>{toast.error(e.message);query.refetch()}})};
 return <div className="px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1100px]"><div className="flex items-end justify-between gap-4"><div><p className="text-sm text-muted-foreground">Personal dashboard</p><h1 className="mt-1 text-3xl font-bold">Business invitations</h1><p className="mt-2 text-sm text-muted-foreground">Review invitations sent to your account.</p></div><select aria-label="Invitation status" className="h-9 rounded-lg border border-input bg-background px-3 text-sm" value={status??""} onChange={e=>{setStatus((e.target.value||undefined) as InviteStatus|undefined);setPage(1)}}><option value="">All statuses</option>{["pending","accepted","rejected","expired","revoked"].map(s=><option key={s}>{s}</option>)}</select></div><div className="mt-7 grid gap-4">{query.isLoading?<LoadingState/>:query.error?<ErrorState error={query.error} onRetry={()=>query.refetch()}/>:query.data?.items.length?query.data.items.map(i=><article key={i.id} className="rounded-xl border border-border bg-card p-5"><div className="flex flex-wrap justify-between gap-4"><div className="flex gap-3">{i.businessId.profile_img?<span className="h-11 w-11 rounded-lg bg-cover bg-center" style={{backgroundImage:`url(${i.businessId.profile_img})`}}/>:<span className="flex h-11 w-11 items-center justify-center rounded-lg bg-primary/10 font-bold text-primary">{i.businessId.name.slice(0,2).toUpperCase()}</span>}<div><h2 className="font-semibold">{i.businessId.name}</h2><p className="text-sm text-muted-foreground">Invited by {i.invitedByUserId.name} as {i.roleId.name}</p></div></div><div className="flex gap-2"><Badge tone={i.status==="accepted"?"good":i.status==="pending"?"warn":"neutral"}>{i.status}</Badge>{i.status==="accepted"&&i.approvalStatus==="pending"?<Badge tone="warn">awaiting role approval</Badge>:null}</div></div><div className="mt-4 rounded-lg bg-muted/40 p-4"><PermissionList permissions={i.roleId.permissions} denied={i.roleId.deniedPermissions}/></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-muted-foreground">Expires {formatDateTime(i.expiresAt)}</p>{i.status==="pending"?<div className="flex gap-2"><Button variant="outline" disabled={Boolean(pendingId)} onClick={()=>act(i.id,"reject")}>Reject</Button><Button disabled={Boolean(pendingId)} onClick={()=>act(i.id,"accept")}>Accept</Button></div>:i.status==="accepted"&&i.approvalStatus!=="pending"?<Button asChild><Link href={`/business/${i.businessId.id}`}>Open business</Link></Button>:null}</div></article>):<p className="rounded-lg border border-dashed p-10 text-center text-sm text-muted-foreground">No invitations found.</p>}</div>{query.data?<Pagination page={page} totalPages={query.data.pagination.totalPages} total={query.data.pagination.total} limit={20} fetching={query.isFetching} onPage={setPage} onLimit={()=>{}}/>:null}</div></div>}
