import type { AuditEvent } from "@/types/generic";

export const auditEvents: AuditEvent[] = [
  {
    id: "aud_001",
    eventId: "evt_payment_created",
    eventType: "payment.created",
    category: "account",
    outcome: "success",
    severity: "info",
    userId: "usr_amara",
    emailHash: null,
    userSessionId: "uses_001",
    authSessionId: "auth_001",
    requestId: "req_01",
    ipAddress: "102.89.23.41",
    userAgent: "Chrome on Windows",
    deviceName: "Office workstation",
    city: "Lagos",
    region: "Lagos",
    country: "Nigeria",
    reason: null,
    metadata: { businessId: "biz_lagos_foods", amount: 2_850_000 },
    createdAt: "2026-06-22T15:30:00.000Z",
  },
  {
    id: "aud_002",
    eventId: "evt_invite_accepted",
    eventType: "invite.accepted",
    category: "account",
    outcome: "success",
    severity: "info",
    userId: "usr_amara",
    emailHash: null,
    userSessionId: "uses_001",
    authSessionId: "auth_001",
    requestId: "req_02",
    ipAddress: "102.89.23.41",
    userAgent: "Chrome on Windows",
    deviceName: "Office workstation",
    city: "Lagos",
    region: "Lagos",
    country: "Nigeria",
    reason: null,
    metadata: { businessId: "biz_eko_health" },
    createdAt: "2026-06-21T09:00:00.000Z",
  },
  {
    id: "aud_003",
    eventId: "evt_session_revoked",
    eventType: "session.revoked",
    category: "session",
    outcome: "success",
    severity: "warning",
    userId: "usr_amara",
    emailHash: null,
    userSessionId: "uses_mobile",
    authSessionId: "auth_mobile",
    requestId: "req_03",
    ipAddress: "197.210.54.9",
    userAgent: "Safari on iOS",
    deviceName: "iPhone 15",
    city: "Abuja",
    region: "FCT",
    country: "Nigeria",
    reason: "User revoked unfamiliar device",
    createdAt: "2026-06-20T18:10:00.000Z",
  },
  {
    id: "aud_004",
    eventId: "evt_login_blocked",
    eventType: "login.blocked",
    category: "authentication",
    outcome: "blocked",
    severity: "critical",
    userId: "usr_amara",
    emailHash: null,
    userSessionId: null,
    authSessionId: null,
    requestId: "req_04",
    ipAddress: "41.203.80.22",
    userAgent: "Unknown browser",
    deviceName: "Unknown device",
    city: "Port Harcourt",
    region: "Rivers",
    country: "Nigeria",
    reason: "OTP challenge failed repeatedly",
    createdAt: "2026-06-19T21:45:00.000Z",
  },
];
